language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - node_modules
env:
  global:
    - CC_TEST_REPORTER_ID=78d0c5eab6f8f0192f830de7204d3d15cea41a8b485d839f86de4b249d84979b
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
install:
  - npm install
  - npm install -g jest
script:
  - npm test
  - npm run build
